services:
  windows:
    image: dockurr/windows
    container_name: linux-mint
    environment:
      MANUAL: "Y"
      VERSION: "https://mirror.freedif.org/LinuxMint/iso/stable/22.3/linuxmint-22.3-xfce-64bit.iso"
      CPU_CORES: "2"
      RAM_SIZE: "8G"
    ports:
      - "8006:8006"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
